version: "3.9"

services:
  # Base de datos MySQL
  mysql:
    image: mysql:8.0
    container_name: multas-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 0578
      MYSQL_DATABASE: db_multas
      MYSQL_USER: multas_user
      MYSQL_PASSWORD: multas_pass
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p0578"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    image: proyecto-final-runtime
    container_name: multas-app
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/db_multas?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: multas_user
      SPRING_DATASOURCE_PASSWORD: multas_pass
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
    ports:
      - "8080:8080"

networks:
  multas-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
