services:
  # Base de datos MySQL
  mysql:
    image: mysql:8.0
    container_name: multas-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 0578
      MYSQL_DATABASE: db_multas
      MYSQL_USER: multas_user
      MYSQL_PASSWORD: multas_pass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - multas-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  multas-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
